using System;

namespace DSHS.CMBHS.Model 
{
/// <summary>
/// Generated By:   NJohn01 using CMBHS Generator v2.6
/// Schema:         CMBHS_DEV5
/// Date Generated: Friday, August 21, 2020
///
/// Template Name:           CMBHSDomainObject.cs	
/// Template Version:        1.0
/// Template Date:           Jan 08, 2008
///
/// Template Description:    This template is used to generate
/// 					the base Domain objects for the DSHS.CMBHS.Model
///
/// Base Object Name:        SU_ASMT_DERIVED_PROBLEMS_VIEW
/// Base Object Type:        View
///
/// Class Information:
/// 	Base ClassName:      DSHS.CMBHS.Model.AbstractDomainObject
/// 	ClassName:           SuAsmtDerivedProblemsViewBase
/// 	Name Space Name:     DSHS.CMBHS.Model
///
/// File Information:
/// 	Template File Name:  CMBHSViewDomain
/// 	Class File Name:         SuAsmtDerivedProblemsViewBase.cs
///
/// </summary>

	public class SuAsmtDerivedProblemsViewBase : AbstractDomainObject
	{

		#region SuAsmtDerivedProblemsViewBase Constructor

		public SuAsmtDerivedProblemsViewBase () : base (){}

		#endregion

		#region Table Attribute Accessors


		public virtual int SuAssessmentNbr{ get; set;}

		#region SuAssessmentNbrSpecified property accessor
		/// <summary>
		/// Used by XmlSerializer when serialized. We use a special pattern to create a Boolean field recognized
		/// by the XmlSerializer, and to apply the XmlIgnoreAttribute to the field. The pattern is created in the
		/// form of propertyNameSpecified. For example, if there is a field named "MyFirstName" you would also
		/// create a field named "MyFirstNameSpecified" that instructs the XmlSerializer whether to generate the
		/// XML element named "MyFirstName". We use this for all nullable properties. This will cause the property
		/// to not render as an XmlElement (otherwise value types like short would render an element's text as -32768).
		/// </summary>
		[System.Xml.Serialization.XmlIgnore]
		public virtual bool SuAssessmentNbrSpecified
		{
			get { return SuAssessmentNbr != int.MinValue; }
		}

		#endregion SuAssessmentNbrSpecified property accessor


		public virtual int GpraAssessmentNbr{ get; set;}

		#region GpraAssessmentNbrSpecified property accessor
		/// <summary>
		/// Used by XmlSerializer when serialized. We use a special pattern to create a Boolean field recognized
		/// by the XmlSerializer, and to apply the XmlIgnoreAttribute to the field. The pattern is created in the
		/// form of propertyNameSpecified. For example, if there is a field named "MyFirstName" you would also
		/// create a field named "MyFirstNameSpecified" that instructs the XmlSerializer whether to generate the
		/// XML element named "MyFirstName". We use this for all nullable properties. This will cause the property
		/// to not render as an XmlElement (otherwise value types like short would render an element's text as -32768).
		/// </summary>
		[System.Xml.Serialization.XmlIgnore]
		public virtual bool GpraAssessmentNbrSpecified
		{
			get { return GpraAssessmentNbr != int.MinValue; }
		}

		#endregion GpraAssessmentNbrSpecified property accessor


		public virtual int ProblemCategory{ get; set;}

		#region ProblemCategorySpecified property accessor
		/// <summary>
		/// Used by XmlSerializer when serialized. We use a special pattern to create a Boolean field recognized
		/// by the XmlSerializer, and to apply the XmlIgnoreAttribute to the field. The pattern is created in the
		/// form of propertyNameSpecified. For example, if there is a field named "MyFirstName" you would also
		/// create a field named "MyFirstNameSpecified" that instructs the XmlSerializer whether to generate the
		/// XML element named "MyFirstName". We use this for all nullable properties. This will cause the property
		/// to not render as an XmlElement (otherwise value types like short would render an element's text as -32768).
		/// </summary>
		[System.Xml.Serialization.XmlIgnore]
		public virtual bool ProblemCategorySpecified
		{
			get { return ProblemCategory != int.MinValue; }
		}

		#endregion ProblemCategorySpecified property accessor

		#endregion Table Attribute Accessors
	}
}
