using System;
using System.ComponentModel;

namespace DSHS.CMBHS.Model 
{
//   <summary>
	// Generated By:   lactbprakash581 using CMBHS Generator v2.6
	// Schema:         CMBHS_TEST3
	// Date Generated: Wednesday, August 09, 2017
//   
/// Template Name:		CMBHSDomainObject.cs	
/// Template Version:	1.0
/// Template Date:		Dec 19, 2007
///
/// Template Description:
/// 	This template is used to generate
/// 	the base Domain objects for the DSHS.CMBHS.Model
///
/// Base Object Name:        SU_ASMT_AXIS_DIAGNOSIS
/// Base Object Type:        Table
///
///  Class Information:
/// 	Base ClassName:      AbstractDomainObject
/// 	ClassName:           SuAsmtAxisDiagnosisBase
/// 	Name Space Name:     DSHS.CMBHS.Model
///
///  File Information:
/// 	Template File Name:  CMBHSTableDomain
/// 	Class File Name:         SuAsmtAxisDiagnosisBase.cs
///
/// Primary Key Name	PrimaryKeyColumnName 
/// SUASMT_AXISDIAGNOSIS_PK SU_ASMT_AXIS_DIAGNOSIS_NBR
///   </summary>

	public class SuAsmtAxisDiagnosisBase : AbstractDomainObject,IAxisDiagnosis
	{

		#region Table Attribute Accessors

		/// <summary>
		/// PrimaryKey property accessor
		/// </summary>
		[System.Xml.Serialization.XmlIgnore]
		public virtual String PrimaryKey{ get; set; }

		/// <summary>
		/// SuAsmtAxisDiagnosisNbr property accessor
		/// </summary>
		[CustomAttribute.Comment("Primary Key - Unique row identifier.")]
		public virtual int SuAsmtAxisDiagnosisNbr{ get; set;}

		/// <summary>
		/// AssessmentDiagnosisNbr property accessor
		/// </summary>
		[CustomAttribute.Comment("This identifier refrences to SU_ASMT_DIAGNOSIS table.")]
		[CustomAttribute.ReferencedClass("DSHS.CMBHS.Model.SuAsmtDiagnosisBase,DSHS.CMBHS.Model")]
		public virtual int AssessmentDiagnosisNbr{ get; set;}

		// Used by XmlSerializer when serialized. We use a special pattern to create a Boolean field recognized
		// by the XmlSerializer, and to apply the XmlIgnoreAttribute to the field. The pattern is created in the
		// form of propertyNameSpecified. For example, if there is a field named "MyFirstName" you would also
		// create a field named "MyFirstNameSpecified" that instructs the XmlSerializer whether to generate the
		// XML element named "MyFirstName". We use this for all nullable properties. This will cause the property
		// to not render as an XmlElement (otherwise value types like short would render an element's text as -32768).
		[System.Xml.Serialization.XmlIgnore]
		public virtual bool AssessmentDiagnosisNbrSpecified
		{
			get { return AssessmentDiagnosisNbr != int.MinValue; }
		}


		/// <summary>
		/// DiagnosisOrder property accessor
		/// </summary>
		[CustomAttribute.Comment("Order of the treatment Service.")]
		public virtual short DiagnosisOrder{ get; set;}

		// Used by XmlSerializer when serialized. We use a special pattern to create a Boolean field recognized
		// by the XmlSerializer, and to apply the XmlIgnoreAttribute to the field. The pattern is created in the
		// form of propertyNameSpecified. For example, if there is a field named "MyFirstName" you would also
		// create a field named "MyFirstNameSpecified" that instructs the XmlSerializer whether to generate the
		// XML element named "MyFirstName". We use this for all nullable properties. This will cause the property
		// to not render as an XmlElement (otherwise value types like short would render an element's text as -32768).
		[System.Xml.Serialization.XmlIgnore]
		public virtual bool DiagnosisOrderSpecified
		{
			get { return DiagnosisOrder != short.MinValue; }
		}


		/// <summary>
		/// Diagnosis property accessor
		/// </summary>
		public virtual int Diagnosis{ get; set;}

		// Used by XmlSerializer when serialized. We use a special pattern to create a Boolean field recognized
		// by the XmlSerializer, and to apply the XmlIgnoreAttribute to the field. The pattern is created in the
		// form of propertyNameSpecified. For example, if there is a field named "MyFirstName" you would also
		// create a field named "MyFirstNameSpecified" that instructs the XmlSerializer whether to generate the
		// XML element named "MyFirstName". We use this for all nullable properties. This will cause the property
		// to not render as an XmlElement (otherwise value types like short would render an element's text as -32768).
		[System.Xml.Serialization.XmlIgnore]
		public virtual bool DiagnosisSpecified
		{
			get { return Diagnosis != int.MinValue; }
		}


		/// <summary>
		/// SuDiagJustification property accessor
		/// </summary>
		[CustomAttribute.Comment("This field identifies the AXIS Diagnosis justification. The code table for this field is SU_DIAG_JUSTIFICATION.")]
		[CustomAttribute.ReferencedClass("DSHS.CMBHS.Model.AxisJustificationTypeBase,DSHS.CMBHS.Model")]
		public virtual short SuDiagJustification{ get; set;}

		// Used by XmlSerializer when serialized. We use a special pattern to create a Boolean field recognized
		// by the XmlSerializer, and to apply the XmlIgnoreAttribute to the field. The pattern is created in the
		// form of propertyNameSpecified. For example, if there is a field named "MyFirstName" you would also
		// create a field named "MyFirstNameSpecified" that instructs the XmlSerializer whether to generate the
		// XML element named "MyFirstName". We use this for all nullable properties. This will cause the property
		// to not render as an XmlElement (otherwise value types like short would render an element's text as -32768).
		[System.Xml.Serialization.XmlIgnore]
		public virtual bool SuDiagJustificationSpecified
		{
			get { return SuDiagJustification != short.MinValue; }
		}


		/// <summary>
		/// CreatedBy property accessor
		/// </summary>
		[CustomAttribute.Comment("This is the tracking number of the person who created the record. This field can be associated with the PERSON table to obtain additional information about the person who created the record.")]
		[CustomAttribute.ReferencedClass("DSHS.CMBHS.Model.PersonBase,DSHS.CMBHS.Model")]
		public virtual int CreatedBy{ get; set;}

		/// <summary>
		/// CreatedDate property accessor
		/// </summary>
		[CustomAttribute.Comment("Date record was created.")]
		public virtual DateTime CreatedDate{ get; set;}

		/// <summary>
		/// UpdatedBy property accessor
		/// </summary>
		[CustomAttribute.Comment("This is the tracking number of the person who updated the record. This field can be associated with the PERSON table to obtain additional information about the person who updated the record.")]
		[CustomAttribute.ReferencedClass("DSHS.CMBHS.Model.PersonBase,DSHS.CMBHS.Model")]
		public virtual int UpdatedBy{ get; set;}

		/// <summary>
		/// UpdatedDate property accessor
		/// </summary>
		[CustomAttribute.Comment("Date record was updated.")]
		public virtual DateTime UpdatedDate{ get; set;}


        public virtual short DiagnosisType { get; set; }

        public virtual string DiagnosisName { get; set; }

        public virtual short AxisJustificationType { get; set; }

		#endregion Table Attribute Accessors
	}
}
