using System;
using System.ComponentModel;

namespace DSHS.CMBHS.Model 
{
//   <summary>
	// Generated By:   lactacheerala712 using CMBHS Generator v2.6
	// Schema:         CMBHSDEV2
	// Date Generated: Friday, March 01, 2013
//   
/// Template Name:		CMBHSDomainObject.cs	
/// Template Version:	1.0
/// Template Date:		Dec 19, 2007
///
/// Template Description:
/// 	This template is used to generate
/// 	the base Domain objects for the DSHS.CMBHS.Model
///
/// Base Object Name:        SUBMISSION_STATUS
/// Base Object Type:        Table
///
///  Class Information:
/// 	Base ClassName:      AbstractDomainObject
/// 	ClassName:           SubmissionStatusBase
/// 	Name Space Name:     DSHS.CMBHS.Model
///
///  File Information:
/// 	Template File Name:  CMBHSTableDomain
/// 	Class File Name:         SubmissionStatusBase.cs
///
/// Primary Key Name	PrimaryKeyColumnName 
/// SYS_C0040771 VALUE_NBR
///   </summary>

	public class SubmissionStatusBase : AbstractDomainObject
	{

		#region Table data Accessors

		public enum Code : short
		{
			Original = 1,
			Correction = 2,
			Cancel = 3,
			Submitted = 4,
			Deleted = 5,
			CancelBillableService = 6,
			ReadyForProcessing = 7,
			NonBillable = 8
		}

		public static short MapDescription(string value)
		{
			if (value.ToLower().CompareTo("original") == 0)
			return (short)Code.Original;
			if (value.ToLower().CompareTo("correction") == 0)
			return (short)Code.Correction;
			if (value.ToLower().CompareTo("cancel") == 0)
			return (short)Code.Cancel;
			if (value.ToLower().CompareTo("submitted") == 0)
			return (short)Code.Submitted;
			if (value.ToLower().CompareTo("deleted") == 0)
			return (short)Code.Deleted;
			if (value.ToLower().CompareTo("cancel due to change in billable service") == 0)
			return (short)Code.CancelBillableService;
			if (value.ToLower().CompareTo("ready for processing") == 0)
			return (short)Code.ReadyForProcessing;
			if (value.ToLower().CompareTo("non-billable") == 0)
			return (short)Code.NonBillable;
			return 0;
		}

		public static string GetDescription(Code value)
		{
			if(value == Code.Original)
				return "Original";
			if(value == Code.Correction)
				return "Correction";
			if(value == Code.Cancel)
				return "Cancel";
			if(value == Code.Submitted)
				return "Submitted";
			if(value == Code.Deleted)
				return "Deleted";
			if(value == Code.CancelBillableService)
				return "Cancel due to change in billable service";
			if(value == Code.ReadyForProcessing)
				return "Ready for Processing";
			if(value == Code.NonBillable)
				return "Non-Billable";
			return string.Empty;
		}

		public static string GetValueCode(Code value)
		{
			if(value == Code.Original)
				return "ORI";
			if(value == Code.Correction)
				return "COR";
			if(value == Code.Cancel)
				return "CNCL";
			if(value == Code.Submitted)
				return "SBMT";
			if(value == Code.Deleted)
				return "DEL";
			if(value == Code.CancelBillableService)
				return "CNBS";
			if(value == Code.ReadyForProcessing)
				return "RDY";
			if(value == Code.NonBillable)
				return "NBILL";
			return string.Empty;
		}

		#endregion Table data Accessors

		#region Table Attribute Accessors

		/// <summary>
		/// PrimaryKey property accessor
		/// </summary>
		[System.Xml.Serialization.XmlIgnore]
		public virtual String PrimaryKey{ get; set; }

		/// <summary>
		/// ValueNbr property accessor
		/// </summary>
		[CustomAttribute.Comment("This field is the tracking number of the code table record.")]
		public virtual short ValueNbr{ get; set;}

		/// <summary>
		/// ValueCode property accessor
		/// </summary>
		[CustomAttribute.Comment("This field is a code that is used for automated data exchange.")]
		public virtual string ValueCode{ get; set;}

		/// <summary>
		/// ValueAbbrv property accessor
		/// </summary>
		[CustomAttribute.Comment("This field is the abbreviation of the code table record.")]
		public virtual string ValueAbbrv{ get; set;}

		/// <summary>
		/// ValueDescription property accessor
		/// </summary>
		[CustomAttribute.Comment("This field is the description of the code table record.")]
		public virtual string ValueDescription{ get; set;}

		/// <summary>
		/// CreatedBy property accessor
		/// </summary>
		[CustomAttribute.Comment("This is the tracking number of the person who created the record. This field can be associated with the PERSON table to obtain additional information about the person who created the record.")]
		public virtual int CreatedBy{ get; set;}

		/// <summary>
		/// CreatedDate property accessor
		/// </summary>
		[CustomAttribute.Comment("Date the record was created.")]
		public virtual DateTime CreatedDate{ get; set;}

		/// <summary>
		/// UpdatedBy property accessor
		/// </summary>
		[CustomAttribute.Comment("This is the tracking number of the person who updated the record. This field can be associated with the PERSON table to obtain additional information about the person who created the record.")]
		public virtual int UpdatedBy{ get; set;}

		/// <summary>
		/// UpdatedDate property accessor
		/// </summary>
		[CustomAttribute.Comment("Date the record was updated.")]
		public virtual DateTime UpdatedDate{ get; set;}

		/// <summary>
		/// EffectiveDate property accessor
		/// </summary>
		[CustomAttribute.Comment("This is the effective date of the code table record.")]
		public virtual DateTime EffectiveDate{ get; set;}

		/// <summary>
		/// ExpirationDate property accessor
		/// </summary>
		[CustomAttribute.Comment("This is the expiration date (if applicable) of the code table record.")]
		public virtual DateTime ExpirationDate{ get; set;}
		#endregion Table Attribute Accessors
	}
}
