using System;
using System.ComponentModel;

namespace DSHS.CMBHS.Model 
{
//   <summary>
	// Generated By:   lactacheerala712 using CMBHS Generator v2.6
	// Schema:         CMBHSDEV2
	// Date Generated: Friday, March 01, 2013
//   
/// Template Name:		CMBHSDomainObject.cs	
/// Template Version:	1.0
/// Template Date:		Dec 19, 2007
///
/// Template Description:
/// 	This template is used to generate
/// 	the base Domain objects for the DSHS.CMBHS.Model
///
/// Base Object Name:        SUBSTANCE
/// Base Object Type:        Table
///
///  Class Information:
/// 	Base ClassName:      AbstractDomainObject
/// 	ClassName:           SubstanceBase
/// 	Name Space Name:     DSHS.CMBHS.Model
///
///  File Information:
/// 	Template File Name:  CMBHSTableDomain
/// 	Class File Name:         SubstanceBase.cs
///
/// Primary Key Name	PrimaryKeyColumnName 
/// SUBSTANCE_PK VALUE_NBR
///   </summary>

	public class SubstanceBase : AbstractDomainObject
	{

		#region Table data Accessors

		public enum Code : short
		{
			None = 1,
			Alcohol = 2,
			Hallucinogens = 3,
			Dmt = 4,
			Lsd = 5,
			MarijuanaHashish = 6,
			Mescaline = 7,
			Peyote = 8,
			PsilocybinMushrooms = 9,
			Stp = 10,
			Inhalants = 11,
			Aerosols = 12,
			AnestheticsNitrousOxideEitherChloroform = 13,
			Nitrites = 14,
			SolventsPaintThinnerGasolineGlue = 15,
			OpiatesAndSynthetics = 16,
			Codeine = 17,
			DarvocetDarvonDPropxyphene = 18,
			DemerolMeperidineHcl = 19,
			DilaudidHydromorphone = 20,
			Heroin = 21,
			MethadoneNonPrescription = 22,
			Oxycodone = 23,
			Pentazocine = 24,
			UltramTramadol = 25,
			VicodinHydrocodone = 26,
			OverTheCounter = 27,
			Asprin = 28,
			BenadrylDiphenhydramine = 29,
			CoughSyrup = 30,
			EphedrinePsuedoephedrine = 31,
			Sominex = 32,
			Sedatives = 33,
			Benzodiazepines = 34,
			AtivanLorazepam = 35,
			DalmaneFlurazepam = 36,
			HalcionTriazolam = 37,
			KlonopinClonazepam = 38,
			LibriumChloridiazepoxide = 39,
			RestorilTemazepam = 40,
			RohypnolFlunitrazepam = 41,
			TranzeneClorazepate = 42,
			ValiumDiazepam = 43,
			XanaxAlprazolam = 44,
			BarbiturateSedatives = 45,
			LuminalPhenobarbital = 46,
			NembutalPentobarbital = 47,
			SeconalSecobarbital = 48,
			TuinalSecobarbitalAmobarbital = 49,
			OtherSedatives = 50,
			DoridenGlutethimide = 51,
			MiltownMeprobamate = 52,
			PcpPhencyclidine = 53,
			PlacidylEthchlorvynol = 54,
			QuaaludeMethaqualone = 55,
			SonataZaleplon = 56,
			Stimulants = 57,
			Amphetamine = 58,
			Benzedrine = 59,
			Cocaine = 60,
			Crack = 61,
			Dexedrine = 62,
			MdmaEcstasy = 63,
			Methamphetamine = 64,
			Preludin = 65,
			RitalinMethylphenidate = 66,
			OtherDrugs = 67,
			AnabolicSteroids = 68,
			DilantinDiphenylhydantoinPhenytoin = 69,
			GhbGblGammaHydroxybutyrateGammaButyrolactone = 70,
			SpecialKKetamine = 72,
			OtherCannabinoids = 73,
			Buprenorphine = 74,
            SyntheticHallucinogens2Cdrugs =75,
            OtherSyntheticStimulantsBathSalts =76 
		}

		public static short MapDescription(string value)
		{
			if (value.ToLower().CompareTo("none") == 0)
			return (short)Code.None;
			if (value.ToLower().CompareTo("alcohol") == 0)
			return (short)Code.Alcohol;
			if (value.ToLower().CompareTo("hallucinogens") == 0)
			return (short)Code.Hallucinogens;
			if (value.ToLower().CompareTo("dmt") == 0)
			return (short)Code.Dmt;
			if (value.ToLower().CompareTo("lsd") == 0)
			return (short)Code.Lsd;
			if (value.ToLower().CompareTo("marijuana/hashish") == 0)
			return (short)Code.MarijuanaHashish;
			if (value.ToLower().CompareTo("mescaline") == 0)
			return (short)Code.Mescaline;
			if (value.ToLower().CompareTo("peyote") == 0)
			return (short)Code.Peyote;
			if (value.ToLower().CompareTo("psilocybin mushrooms") == 0)
			return (short)Code.PsilocybinMushrooms;
			if (value.ToLower().CompareTo("stp") == 0)
			return (short)Code.Stp;
			if (value.ToLower().CompareTo("inhalants") == 0)
			return (short)Code.Inhalants;
			if (value.ToLower().CompareTo("aerosols") == 0)
			return (short)Code.Aerosols;
			if (value.ToLower().CompareTo("anesthetics (nitrous oxide, either, chloroform)") == 0)
			return (short)Code.AnestheticsNitrousOxideEitherChloroform;
			if (value.ToLower().CompareTo("nitrites") == 0)
			return (short)Code.Nitrites;
			if (value.ToLower().CompareTo("solvents (paint thinner, gasoline, glue)") == 0)
			return (short)Code.SolventsPaintThinnerGasolineGlue;
			if (value.ToLower().CompareTo("opiates and synthetics") == 0)
			return (short)Code.OpiatesAndSynthetics;
			if (value.ToLower().CompareTo("codeine") == 0)
			return (short)Code.Codeine;
			if (value.ToLower().CompareTo("darvocet darvon (d-propxyphene)") == 0)
			return (short)Code.DarvocetDarvonDPropxyphene;
			if (value.ToLower().CompareTo("demerol (meperidine hcl)") == 0)
			return (short)Code.DemerolMeperidineHcl;
			if (value.ToLower().CompareTo("dilaudid (hydromorphone)") == 0)
			return (short)Code.DilaudidHydromorphone;
			if (value.ToLower().CompareTo("heroin") == 0)
			return (short)Code.Heroin;
			if (value.ToLower().CompareTo("methadone (non-prescription)") == 0)
			return (short)Code.MethadoneNonPrescription;
			if (value.ToLower().CompareTo("oxycodone") == 0)
			return (short)Code.Oxycodone;
			if (value.ToLower().CompareTo("pentazocine") == 0)
			return (short)Code.Pentazocine;
			if (value.ToLower().CompareTo("ultram (tramadol)") == 0)
			return (short)Code.UltramTramadol;
			if (value.ToLower().CompareTo("vicodin (hydrocodone)") == 0)
			return (short)Code.VicodinHydrocodone;
			if (value.ToLower().CompareTo("over-the-counter") == 0)
			return (short)Code.OverTheCounter;
			if (value.ToLower().CompareTo("asprin") == 0)
			return (short)Code.Asprin;
			if (value.ToLower().CompareTo("benadryl (diphenhydramine)") == 0)
			return (short)Code.BenadrylDiphenhydramine;
			if (value.ToLower().CompareTo("cough syrup") == 0)
			return (short)Code.CoughSyrup;
			if (value.ToLower().CompareTo("ephedrine/psuedoephedrine") == 0)
			return (short)Code.EphedrinePsuedoephedrine;
			if (value.ToLower().CompareTo("sominex") == 0)
			return (short)Code.Sominex;
			if (value.ToLower().CompareTo("sedatives") == 0)
			return (short)Code.Sedatives;
			if (value.ToLower().CompareTo("benzodiazepines") == 0)
			return (short)Code.Benzodiazepines;
			if (value.ToLower().CompareTo("ativan (lorazepam)") == 0)
			return (short)Code.AtivanLorazepam;
			if (value.ToLower().CompareTo("dalmane (flurazepam)") == 0)
			return (short)Code.DalmaneFlurazepam;
			if (value.ToLower().CompareTo("halcion (triazolam)") == 0)
			return (short)Code.HalcionTriazolam;
			if (value.ToLower().CompareTo("klonopin (clonazepam)") == 0)
			return (short)Code.KlonopinClonazepam;
			if (value.ToLower().CompareTo("librium (chloridiazepoxide)") == 0)
			return (short)Code.LibriumChloridiazepoxide;
			if (value.ToLower().CompareTo("restoril (temazepam)") == 0)
			return (short)Code.RestorilTemazepam;
			if (value.ToLower().CompareTo("rohypnol (flunitrazepam)") == 0)
			return (short)Code.RohypnolFlunitrazepam;
			if (value.ToLower().CompareTo("tranzene (clorazepate)") == 0)
			return (short)Code.TranzeneClorazepate;
			if (value.ToLower().CompareTo("valium (diazepam)") == 0)
			return (short)Code.ValiumDiazepam;
			if (value.ToLower().CompareTo("xanax (alprazolam)") == 0)
			return (short)Code.XanaxAlprazolam;
			if (value.ToLower().CompareTo("barbiturate sedatives") == 0)
			return (short)Code.BarbiturateSedatives;
			if (value.ToLower().CompareTo("luminal (phenobarbital)") == 0)
			return (short)Code.LuminalPhenobarbital;
			if (value.ToLower().CompareTo("nembutal (pentobarbital)") == 0)
			return (short)Code.NembutalPentobarbital;
			if (value.ToLower().CompareTo("seconal (secobarbital)") == 0)
			return (short)Code.SeconalSecobarbital;
			if (value.ToLower().CompareTo("tuinal (secobarbital/amobarbital)") == 0)
			return (short)Code.TuinalSecobarbitalAmobarbital;
			if (value.ToLower().CompareTo("other sedatives") == 0)
			return (short)Code.OtherSedatives;
			if (value.ToLower().CompareTo("doriden (glutethimide)") == 0)
			return (short)Code.DoridenGlutethimide;
			if (value.ToLower().CompareTo("miltown (meprobamate)") == 0)
			return (short)Code.MiltownMeprobamate;
			if (value.ToLower().CompareTo("pcp (phencyclidine)") == 0)
			return (short)Code.PcpPhencyclidine;
			if (value.ToLower().CompareTo("placidyl (ethchlorvynol)") == 0)
			return (short)Code.PlacidylEthchlorvynol;
			if (value.ToLower().CompareTo("quaalude (methaqualone)") == 0)
			return (short)Code.QuaaludeMethaqualone;
			if (value.ToLower().CompareTo("sonata (zaleplon)") == 0)
			return (short)Code.SonataZaleplon;
			if (value.ToLower().CompareTo("stimulants") == 0)
			return (short)Code.Stimulants;
			if (value.ToLower().CompareTo("amphetamine") == 0)
			return (short)Code.Amphetamine;
			if (value.ToLower().CompareTo("benzedrine") == 0)
			return (short)Code.Benzedrine;
			if (value.ToLower().CompareTo("cocaine") == 0)
			return (short)Code.Cocaine;
			if (value.ToLower().CompareTo("crack") == 0)
			return (short)Code.Crack;
			if (value.ToLower().CompareTo("dexedrine") == 0)
			return (short)Code.Dexedrine;
			if (value.ToLower().CompareTo("mdma/ecstasy (methylenedioxymethamphetamine)") == 0)
			return (short)Code.MdmaEcstasy;
			if (value.ToLower().CompareTo("methamphetamine") == 0)
			return (short)Code.Methamphetamine;
			if (value.ToLower().CompareTo("preludin") == 0)
			return (short)Code.Preludin;
			if (value.ToLower().CompareTo("ritalin (methylphenidate)") == 0)
			return (short)Code.RitalinMethylphenidate;
			if (value.ToLower().CompareTo("other drugs") == 0)
			return (short)Code.OtherDrugs;
			if (value.ToLower().CompareTo("anabolic steroids") == 0)
			return (short)Code.AnabolicSteroids;
			if (value.ToLower().CompareTo("dilantin (diphenylhydantoin/phenytoin)") == 0)
			return (short)Code.DilantinDiphenylhydantoinPhenytoin;
			if (value.ToLower().CompareTo("ghb/gbl (gamma-hydroxybutyrate, gamma-butyrolactone)") == 0)
			return (short)Code.GhbGblGammaHydroxybutyrateGammaButyrolactone;
			if (value.ToLower().CompareTo("special k (ketamine)") == 0)
			return (short)Code.SpecialKKetamine;
			if (value.ToLower().CompareTo("other cannabinoids") == 0)
			return (short)Code.OtherCannabinoids;
			if (value.ToLower().CompareTo("buprenorphine") == 0)
			return (short)Code.Buprenorphine;
			return 0;
		}

		public static string GetDescription(Code value)
		{
			if(value == Code.None)
				return "None";
			if(value == Code.Alcohol)
				return "Alcohol";
			if(value == Code.Hallucinogens)
				return "Hallucinogens";
			if(value == Code.Dmt)
				return "DMT";
			if(value == Code.Lsd)
				return "LSD";
			if(value == Code.MarijuanaHashish)
				return "Marijuana/Hashish";
			if(value == Code.Mescaline)
				return "Mescaline";
			if(value == Code.Peyote)
				return "Peyote";
			if(value == Code.PsilocybinMushrooms)
				return "Psilocybin Mushrooms";
			if(value == Code.Stp)
				return "STP";
			if(value == Code.Inhalants)
				return "Inhalants";
			if(value == Code.Aerosols)
				return "Aerosols";
			if(value == Code.AnestheticsNitrousOxideEitherChloroform)
				return "Anesthetics (Nitrous Oxide, Either, Chloroform)";
			if(value == Code.Nitrites)
				return "Nitrites";
			if(value == Code.SolventsPaintThinnerGasolineGlue)
				return "Solvents (Paint Thinner, Gasoline, Glue)";
			if(value == Code.OpiatesAndSynthetics)
				return "Opiates and Synthetics";
			if(value == Code.Codeine)
				return "Codeine";
			if(value == Code.DarvocetDarvonDPropxyphene)
				return "Darvocet Darvon (D-Propxyphene)";
			if(value == Code.DemerolMeperidineHcl)
				return "Demerol (Meperidine Hcl)";
			if(value == Code.DilaudidHydromorphone)
				return "Dilaudid (Hydromorphone)";
			if(value == Code.Heroin)
				return "Heroin";
			if(value == Code.MethadoneNonPrescription)
				return "Methadone (Non-Prescription)";
			if(value == Code.Oxycodone)
				return "Oxycodone";
			if(value == Code.Pentazocine)
				return "Pentazocine";
			if(value == Code.UltramTramadol)
				return "Ultram (Tramadol)";
			if(value == Code.VicodinHydrocodone)
				return "Vicodin (Hydrocodone)";
			if(value == Code.OverTheCounter)
				return "Over-the-counter";
			if(value == Code.Asprin)
				return "Asprin";
			if(value == Code.BenadrylDiphenhydramine)
				return "Benadryl (Diphenhydramine)";
			if(value == Code.CoughSyrup)
				return "Cough Syrup";
			if(value == Code.EphedrinePsuedoephedrine)
				return "Ephedrine/Psuedoephedrine";
			if(value == Code.Sominex)
				return "Sominex";
			if(value == Code.Sedatives)
				return "Sedatives";
			if(value == Code.Benzodiazepines)
				return "Benzodiazepines";
			if(value == Code.AtivanLorazepam)
				return "Ativan (Lorazepam)";
			if(value == Code.DalmaneFlurazepam)
				return "Dalmane (Flurazepam)";
			if(value == Code.HalcionTriazolam)
				return "Halcion (Triazolam)";
			if(value == Code.KlonopinClonazepam)
				return "Klonopin (Clonazepam)";
			if(value == Code.LibriumChloridiazepoxide)
				return "Librium (Chloridiazepoxide)";
			if(value == Code.RestorilTemazepam)
				return "Restoril (Temazepam)";
			if(value == Code.RohypnolFlunitrazepam)
				return "Rohypnol (Flunitrazepam)";
			if(value == Code.TranzeneClorazepate)
				return "Tranzene (Clorazepate)";
			if(value == Code.ValiumDiazepam)
				return "Valium (Diazepam)";
			if(value == Code.XanaxAlprazolam)
				return "Xanax (Alprazolam)";
			if(value == Code.BarbiturateSedatives)
				return "Barbiturate Sedatives";
			if(value == Code.LuminalPhenobarbital)
				return "Luminal (Phenobarbital)";
			if(value == Code.NembutalPentobarbital)
				return "Nembutal (Pentobarbital)";
			if(value == Code.SeconalSecobarbital)
				return "Seconal (Secobarbital)";
			if(value == Code.TuinalSecobarbitalAmobarbital)
				return "Tuinal (Secobarbital/Amobarbital)";
			if(value == Code.OtherSedatives)
				return "Other Sedatives";
			if(value == Code.DoridenGlutethimide)
				return "Doriden (Glutethimide)";
			if(value == Code.MiltownMeprobamate)
				return "Miltown (Meprobamate)";
			if(value == Code.PcpPhencyclidine)
				return "PCP (Phencyclidine)";
			if(value == Code.PlacidylEthchlorvynol)
				return "Placidyl (Ethchlorvynol)";
			if(value == Code.QuaaludeMethaqualone)
				return "Quaalude (Methaqualone)";
			if(value == Code.SonataZaleplon)
				return "Sonata (Zaleplon)";
			if(value == Code.Stimulants)
				return "Stimulants";
			if(value == Code.Amphetamine)
				return "Amphetamine";
			if(value == Code.Benzedrine)
				return "Benzedrine";
			if(value == Code.Cocaine)
				return "Cocaine";
			if(value == Code.Crack)
				return "Crack";
			if(value == Code.Dexedrine)
				return "Dexedrine";
			if(value == Code.MdmaEcstasy)
				return "MDMA/Ecstasy (Methylenedioxymethamphetamine)";
			if(value == Code.Methamphetamine)
				return "Methamphetamine";
			if(value == Code.Preludin)
				return "Preludin";
			if(value == Code.RitalinMethylphenidate)
				return "Ritalin (Methylphenidate)";
			if(value == Code.OtherDrugs)
				return "Other Drugs";
			if(value == Code.AnabolicSteroids)
				return "Anabolic Steroids";
			if(value == Code.DilantinDiphenylhydantoinPhenytoin)
				return "Dilantin (Diphenylhydantoin/Phenytoin)";
			if(value == Code.GhbGblGammaHydroxybutyrateGammaButyrolactone)
				return "GHB/GBL (Gamma-Hydroxybutyrate, Gamma-Butyrolactone)";
			if(value == Code.SpecialKKetamine)
				return "Special K (Ketamine)";
			if(value == Code.OtherCannabinoids)
				return "Other Cannabinoids";
			if(value == Code.Buprenorphine)
				return "Buprenorphine";
			return string.Empty;
		}

		public static string GetValueCode(Code value)
		{
			if(value == Code.None)
				return "NONE";
			if(value == Code.Alcohol)
				return "ALCHL";
			if(value == Code.Hallucinogens)
				return "HALCG";
			if(value == Code.Dmt)
				return "DMT";
			if(value == Code.Lsd)
				return "LSD";
			if(value == Code.MarijuanaHashish)
				return "POT";
			if(value == Code.Mescaline)
				return "MESCL";
			if(value == Code.Peyote)
				return "PEYOT";
			if(value == Code.PsilocybinMushrooms)
				return "PSLCB";
			if(value == Code.Stp)
				return "STP";
			if(value == Code.Inhalants)
				return "INHLT";
			if(value == Code.Aerosols)
				return "AEROS";
			if(value == Code.AnestheticsNitrousOxideEitherChloroform)
				return "ANSTC";
			if(value == Code.Nitrites)
				return "NITRT";
			if(value == Code.SolventsPaintThinnerGasolineGlue)
				return "SOLVT";
			if(value == Code.OpiatesAndSynthetics)
				return "OPIAT";
			if(value == Code.Codeine)
				return "CODNE";
			if(value == Code.DarvocetDarvonDPropxyphene)
				return "DARV";
			if(value == Code.DemerolMeperidineHcl)
				return "DMRL";
			if(value == Code.DilaudidHydromorphone)
				return "DLAUD";
			if(value == Code.Heroin)
				return "HERON";
			if(value == Code.MethadoneNonPrescription)
				return "MTHDN";
			if(value == Code.Oxycodone)
				return "OXYCD";
			if(value == Code.Pentazocine)
				return "PNTZC";
			if(value == Code.UltramTramadol)
				return "ULTRM";
			if(value == Code.VicodinHydrocodone)
				return "VICDN";
			if(value == Code.OverTheCounter)
				return "OTC";
			if(value == Code.Asprin)
				return "ASPRN";
			if(value == Code.BenadrylDiphenhydramine)
				return "BNDRL";
			if(value == Code.CoughSyrup)
				return "CGHSP";
			if(value == Code.EphedrinePsuedoephedrine)
				return "EPHDR";
			if(value == Code.Sominex)
				return "SOMNX";
			if(value == Code.Sedatives)
				return "SEDTV";
			if(value == Code.Benzodiazepines)
				return "BNZDP";
			if(value == Code.AtivanLorazepam)
				return "ATVN";
			if(value == Code.DalmaneFlurazepam)
				return "DALMN";
			if(value == Code.HalcionTriazolam)
				return "HALCN";
			if(value == Code.KlonopinClonazepam)
				return "KLNPN";
			if(value == Code.LibriumChloridiazepoxide)
				return "LIBRM";
			if(value == Code.RestorilTemazepam)
				return "RSTRL";
			if(value == Code.RohypnolFlunitrazepam)
				return "ROHYP";
			if(value == Code.TranzeneClorazepate)
				return "TRNZN";
			if(value == Code.ValiumDiazepam)
				return "DZPAM";
			if(value == Code.XanaxAlprazolam)
				return "XANAX";
			if(value == Code.BarbiturateSedatives)
				return "BARB";
			if(value == Code.LuminalPhenobarbital)
				return "LUMNL";
			if(value == Code.NembutalPentobarbital)
				return "NMBTL";
			if(value == Code.SeconalSecobarbital)
				return "SECNL";
			if(value == Code.TuinalSecobarbitalAmobarbital)
				return "TUINL";
			if(value == Code.OtherSedatives)
				return "OSDTV";
			if(value == Code.DoridenGlutethimide)
				return "DORDN";
			if(value == Code.MiltownMeprobamate)
				return "MLTWN";
			if(value == Code.PcpPhencyclidine)
				return "PCP";
			if(value == Code.PlacidylEthchlorvynol)
				return "PLCDL";
			if(value == Code.QuaaludeMethaqualone)
				return "QLUDE";
			if(value == Code.SonataZaleplon)
				return "SONTA";
			if(value == Code.Stimulants)
				return "STMLT";
			if(value == Code.Amphetamine)
				return "AMPHT";
			if(value == Code.Benzedrine)
				return "BNZDR";
			if(value == Code.Cocaine)
				return "COKE";
			if(value == Code.Crack)
				return "CRACK";
			if(value == Code.Dexedrine)
				return "DXDRN";
			if(value == Code.MdmaEcstasy)
				return "MDMA";
			if(value == Code.Methamphetamine)
				return "MTHAM";
			if(value == Code.Preludin)
				return "PRLDN";
			if(value == Code.RitalinMethylphenidate)
				return "RITLN";
			if(value == Code.OtherDrugs)
				return "OTHER";
			if(value == Code.AnabolicSteroids)
				return "SROID";
			if(value == Code.DilantinDiphenylhydantoinPhenytoin)
				return "DILTN";
			if(value == Code.GhbGblGammaHydroxybutyrateGammaButyrolactone)
				return "GHB";
			if(value == Code.SpecialKKetamine)
				return "KTAMN";
			if(value == Code.OtherCannabinoids)
				return "OTCN";
			if(value == Code.Buprenorphine)
				return "BUP";
			return string.Empty;
		}

		#endregion Table data Accessors

		#region Table Attribute Accessors

		/// <summary>
		/// PrimaryKey property accessor
		/// </summary>
		[System.Xml.Serialization.XmlIgnore]
		public virtual String PrimaryKey{ get; set; }

		/// <summary>
		/// ValueNbr property accessor
		/// </summary>
		[CustomAttribute.Comment("This field is the tracking number of the code table record.")]
		public virtual short ValueNbr{ get; set;}

		/// <summary>
		/// ValueAbbrv property accessor
		/// </summary>
		[CustomAttribute.Comment("This field is the abbreviation of the code table record.                                             ")]
		public virtual string ValueAbbrv{ get; set;}

		/// <summary>
		/// ValueDescription property accessor
		/// </summary>
		[CustomAttribute.Comment("This field is the description of the code table record.")]
		public virtual string ValueDescription{ get; set;}

		/// <summary>
		/// CreatedBy property accessor
		/// </summary>
		[CustomAttribute.Comment("This is the tracking number of the person who created the record. This field can be associated with the PERSON table to obtain additional information about the person who created the record.")]
		public virtual int CreatedBy{ get; set;}

		/// <summary>
		/// CreatedDate property accessor
		/// </summary>
		[CustomAttribute.Comment("Date record was created.")]
		public virtual DateTime CreatedDate{ get; set;}

		/// <summary>
		/// UpdatedBy property accessor
		/// </summary>
		[CustomAttribute.Comment("This is the tracking number of the person who updated the record. This field can be associated with the PERSON table to obtain additional information about the person who updated the record.                                              ")]
		public virtual int UpdatedBy{ get; set;}

		/// <summary>
		/// UpdatedDate property accessor
		/// </summary>
		[CustomAttribute.Comment("Date record was updated.")]
		public virtual DateTime UpdatedDate{ get; set;}

		/// <summary>
		/// ValueCode property accessor
		/// </summary>
		[CustomAttribute.Comment("This field is a code that is used for automated data exchange.")]
		public virtual string ValueCode{ get; set;}

		/// <summary>
		/// EffectiveDate property accessor
		/// </summary>
		[CustomAttribute.Comment("This is the effective date of the code table record.")]
		public virtual DateTime EffectiveDate{ get; set;}

		/// <summary>
		/// ExpirationDate property accessor
		/// </summary>
		[CustomAttribute.Comment("This is the expiration date (if applicable) of the code table record.")]
		public virtual DateTime ExpirationDate{ get; set;}

		/// <summary>
		/// ParentValueNbr property accessor
		/// </summary>
		[CustomAttribute.Comment("this field to Identify the Parent Child Information")]
		public virtual short ParentValueNbr{ get; set;}
		#endregion Table Attribute Accessors
	}
}
