using System;
using System.ComponentModel;

namespace DSHS.CMBHS.Model 
{
//   <summary>
	// Generated By:   LACTmnimmala933 using CMBHS Generator v2.6
	// Schema:         CMBHS_DEV3
	// Date Generated: Thursday, June 22, 2017
//   
/// Template Name:		CMBHSDomainObject.cs	
/// Template Version:	1.0
/// Template Date:		Dec 19, 2007
///
/// Template Description:
/// 	This template is used to generate
/// 	the base Domain objects for the DSHS.CMBHS.Model
///
/// Base Object Name:        SU_CONTACT_TYPE
/// Base Object Type:        Table
///
///  Class Information:
/// 	Base ClassName:      AbstractDomainObject
/// 	ClassName:           SuContactTypeBase
/// 	Name Space Name:     DSHS.CMBHS.Model
///
///  File Information:
/// 	Template File Name:  CMBHSTableDomain
/// 	Class File Name:         SuContactTypeBase.cs
///
/// Primary Key Name	PrimaryKeyColumnName 
/// SUCONTACTTYPE_PK VALUE_NBR
///   </summary>

	public class SuContactTypeBase : AbstractDomainObject
	{

		#region Table data Accessors

		public enum Code : short
		{
			FaceToFace = 1,
			Telehealth = 2,
			Telephone = 3,
			WithClient = 4,
			WithFamily = 5,
			WithCollateral = 6,
			VoiceMail = 7,
			None = 8,
			Other = 9
		}

		public static short MapDescription(string value)
		{
			if (value.ToLower().CompareTo("face to face") == 0)
			return (short)Code.FaceToFace;
			if (value.ToLower().CompareTo("telehealth") == 0)
			return (short)Code.Telehealth;
			if (value.ToLower().CompareTo("telephone") == 0)
			return (short)Code.Telephone;
			if (value.ToLower().CompareTo("with client") == 0)
			return (short)Code.WithClient;
			if (value.ToLower().CompareTo("with family") == 0)
			return (short)Code.WithFamily;
			if (value.ToLower().CompareTo("with collateral") == 0)
			return (short)Code.WithCollateral;
			if (value.ToLower().CompareTo("voice mail") == 0)
			return (short)Code.VoiceMail;
			if (value.ToLower().CompareTo("none") == 0)
			return (short)Code.None;
			if (value.ToLower().CompareTo("other") == 0)
			return (short)Code.Other;
			return 0;
		}

		public static string GetDescription(Code value)
		{
			if(value == Code.FaceToFace)
				return "Face to Face";
			if(value == Code.Telehealth)
				return "Telehealth";
			if(value == Code.Telephone)
				return "Telephone";
			if(value == Code.WithClient)
				return "With Client";
			if(value == Code.WithFamily)
				return "With Family";
			if(value == Code.WithCollateral)
				return "With Collateral";
			if(value == Code.VoiceMail)
				return "Voice Mail";
			if(value == Code.None)
				return "None";
			if(value == Code.Other)
				return "Other";
			return string.Empty;
		}

		public static string GetValueCode(Code value)
		{
			if(value == Code.FaceToFace)
				return "";
			if(value == Code.Telehealth)
				return "";
			if(value == Code.Telephone)
				return "";
			if(value == Code.WithClient)
				return "";
			if(value == Code.WithFamily)
				return "";
			if(value == Code.WithCollateral)
				return "";
			if(value == Code.VoiceMail)
				return "";
			if(value == Code.None)
				return "";
			if(value == Code.Other)
				return "";
			return string.Empty;
		}

		#endregion Table data Accessors

		#region Table Attribute Accessors

		/// <summary>
		/// PrimaryKey property accessor
		/// </summary>
		[System.Xml.Serialization.XmlIgnore]
		public virtual String PrimaryKey{ get; set; }

		/// <summary>
		/// ValueNbr property accessor
		/// </summary>
		public virtual short ValueNbr{ get; set;}

		/// <summary>
		/// ValueAbbrv property accessor
		/// </summary>
		public virtual string ValueAbbrv{ get; set;}

		/// <summary>
		/// ValueDescription property accessor
		/// </summary>
		public virtual string ValueDescription{ get; set;}

		/// <summary>
		/// ValueCode property accessor
		/// </summary>
		public virtual string ValueCode{ get; set;}

		/// <summary>
		/// EffectiveDate property accessor
		/// </summary>
		public virtual DateTime EffectiveDate{ get; set;}

		/// <summary>
		/// ExpirationDate property accessor
		/// </summary>
		public virtual DateTime ExpirationDate{ get; set;}

		/// <summary>
		/// CreatedBy property accessor
		/// </summary>
		[CustomAttribute.Comment("This is the tracking number of the person who created the record. This field can be associated with the PERSON table to obtain additional information about the person who created the record.")]
		public virtual int CreatedBy{ get; set;}

		/// <summary>
		/// CreatedDate property accessor
		/// </summary>
		[CustomAttribute.Comment("Date record was created.")]
		public virtual DateTime CreatedDate{ get; set;}

		/// <summary>
		/// UpdatedBy property accessor
		/// </summary>
		[CustomAttribute.Comment("This is the tracking number of the person who updated the record. This field can be associated with the PERSON table to obtain additional information about the person who updated the record.")]
		public virtual int UpdatedBy{ get; set;}

		/// <summary>
		/// UpdatedDate property accessor
		/// </summary>
		[CustomAttribute.Comment("Date record was updated.")]
		public virtual DateTime UpdatedDate{ get; set;}
		#endregion Table Attribute Accessors
	}
}
